// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// TaskStatusTodo is a TaskStatus of type todo.
	TaskStatusTodo TaskStatus = "todo"
	// TaskStatusInProgress is a TaskStatus of type in_progress.
	TaskStatusInProgress TaskStatus = "in_progress"
	// TaskStatusComplete is a TaskStatus of type complete.
	TaskStatusComplete TaskStatus = "complete"
)

var ErrInvalidTaskStatus = errors.New("not a valid TaskStatus")

// String implements the Stringer interface.
func (x TaskStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TaskStatus) IsValid() bool {
	_, err := ParseTaskStatus(string(x))
	return err == nil
}

var _TaskStatusValue = map[string]TaskStatus{
	"todo":        TaskStatusTodo,
	"in_progress": TaskStatusInProgress,
	"complete":    TaskStatusComplete,
}

// ParseTaskStatus attempts to convert a string to a TaskStatus.
func ParseTaskStatus(name string) (TaskStatus, error) {
	if x, ok := _TaskStatusValue[name]; ok {
		return x, nil
	}
	return TaskStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidTaskStatus)
}
